# Generated by Django 6.0.4 on 2026-04-18 23:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('outlet_name', models.CharField(default='School Canteen', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='wallet.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paisakid_children', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='wallet.school')),
            ],
            options={
                'ordering': ['student_code'],
            },
        ),
        migrations.CreateModel(
            name='PhotoChallengeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('choice_student_ids', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_challenges', to='wallet.student')),
            ],
        ),
        migrations.CreateModel(
            name='ParentAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='warning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paisakid_alerts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='wallet.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('spent_pkr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spends', to='wallet.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentControls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit_pkr', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=12)),
                ('purchases_enabled', models.BooleanField(default=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='wallet.student')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('topup', 'Top-up'), ('purchase', 'Purchase')], max_length=20)),
                ('amount_pkr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('merchant_name', models.CharField(blank=True, max_length=200)),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('flagged', 'Flagged')], default='success', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_transactions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_pkr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='wallet.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'student_code'), name='uniq_student_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='dailyspend',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='uniq_daily_spend_per_day'),
        ),
    ]
